// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\Contact.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Contact : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\Contact.tt"
 FileName=@"\{0}.Module\BusinessObjects\Contact.cs"; 
            
            #line default
            #line hidden
            this.Write("\r\nusing System;\r\nusing System.Linq;\r\nusing System.Text;\r\nusing DevExpress.Xpo;\r\nu" +
                    "sing DevExpress.ExpressApp;\r\nusing System.ComponentModel;\r\nusing DevExpress.Expr" +
                    "essApp.DC;\r\nusing DevExpress.Data.Filtering;\r\nusing DevExpress.Persistent.Base;\r" +
                    "\nusing System.Collections.Generic;\r\nusing DevExpress.ExpressApp.Model;\r\nusing De" +
                    "vExpress.Persistent.BaseImpl;\r\nusing DevExpress.Persistent.Validation;\r\nusing De" +
                    "vExpress.ExpressApp.Editors;\r\nusing System.Diagnostics;\r\nusing DevExpress.Persis" +
                    "tent.Base.General;\r\nusing DevExpress.ExpressApp.SystemModule;\r\n\r\nnamespace dxTes" +
                    "tSolution.Module.BusinessObjects {\r\n     [DefaultClassOptions]\r\n\t  [DebuggerDisp" +
                    "lay(\"FirstName: {FirstName}\")]\r\n    public class Contact : BaseObject { \r\n      " +
                    "  public Contact(Session session)\r\n            : base(session) {\r\n        }\r\n   " +
                    "     public override void AfterConstruction() {\r\n            base.AfterConstruct" +
                    "ion();\r\n        }\r\n        string firstName;\r\n        public string FirstName {\r" +
                    "\n            get {\r\n                return firstName;\r\n            }\r\n          " +
                    "  set {\r\n                SetPropertyValue(nameof(FirstName), ref firstName, valu" +
                    "e);\r\n            }\r\n        }\r\n        string lastName;\r\n        public string L" +
                    "astName {\r\n            get {\r\n                return lastName;\r\n            }\r\n " +
                    "           set {\r\n                SetPropertyValue(nameof(LastName), ref lastNam" +
                    "e, value);\r\n            }\r\n        }\r\n\t\tint age;\r\n        public int Age {\r\n    " +
                    "        get {\r\n                return age;\r\n            }\r\n            set {\r\n  " +
                    "              SetPropertyValue(nameof(Age), ref age, value);\r\n            }\r\n   " +
                    "     }\r\n        // DateTime _birthDate;\r\n        // public DateTime BirthDate {\r" +
                    "\n        // get {\r\n        // return _birthDate;\r\n        // }\r\n        // set {" +
                    "\r\n        // SetPropertyValue(nameof(BirthDate), ref _birthDate, value);\r\n      " +
                    "  // }\r\n        // }\r\n\t\t\r\n\t\t");
            
            #line 73 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\Contact.tt"
 if (HasOffice){ 
            
            #line default
            #line hidden
            this.Write(@"		byte[] _text;
        [EditorAlias(EditorAliases.RichTextPropertyEditor)]
        public byte[] Text {
            get {
                return _text;
            }
            set {
                SetPropertyValue(nameof(Text), ref _text, value);
            }
        }

		private byte[] data;
        [EditorAlias(EditorAliases.SpreadsheetPropertyEditor)] 
        public byte[] Data { 
			get { return data; }
			set { SetPropertyValue(nameof(Data), ref data, value); }
		}
		");
            
            #line 91 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\Contact.tt"
 } 
            
            #line default
            #line hidden
            this.Write("       \r\n        [Association(\"Contact-Tasks\")]\r\n        public XPCollection<MyTa" +
                    "sk> Tasks {\r\n            get {\r\n                return GetCollection<MyTask>(nam" +
                    "eof(Tasks));\r\n            }\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
