// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\GlobalAsax.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class GlobalAsax : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\GlobalAsax.tt"
 FileName=@"\{0}.Web\Global.asax.cs"; 
            
            #line default
            #line hidden
            this.Write(@"
using System;
using System.Configuration;
using System.Web.Configuration;
using System.Web;

using DevExpress.ExpressApp;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.ExpressApp.Security;
using DevExpress.ExpressApp.Web;
using DevExpress.Web;
using System.Web.Routing;

namespace dxTestSolution.Web {
    public class Global : System.Web.HttpApplication {
        public Global() {
            InitializeComponent();
        }
        protected void Application_Start(Object sender, EventArgs e) {
			RouteTable.Routes.RegisterXafRoutes();
            ASPxWebControl.CallbackError += new EventHandler(Application_Error);
#if EASYTEST
            DevExpress.ExpressApp.Web.TestScripts.TestScriptsManager.EasyTestEnabled = true;
#endif
        }
        protected void Session_Start(Object sender, EventArgs e) {
		    Tracing.Initialize();
            WebApplication.SetInstance(Session, new dxTestSolutionAspNetApplication());
			");
            
            #line 36 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\GlobalAsax.tt"
 if (HasSecurity){ 
            
            #line default
            #line hidden
            this.Write("               SecurityStrategy security = WebApplication.Instance.GetSecurityStr" +
                    "ategy();\r\n            security.RegisterXPOAdapterProviders();\r\n\t\t\t");
            
            #line 39 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\GlobalAsax.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tDevExpress.ExpressApp.Web.Templates.DefaultVerticalTemplateContentNew.ClearSiz" +
                    "eLimit();\r\n            WebApplication.Instance.SwitchToNewStyle();\r\n\t\t\t");
            
            #line 42 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\GlobalAsax.tt"
 if (HasSecurity){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tWebApplication.Instance.LastLogonParametersRead += MyApplication_LastLogonPara" +
                    "metersRead;\r\n");
            
            #line 44 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\GlobalAsax.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"			
            if(ConfigurationManager.ConnectionStrings[""ConnectionString""] != null) {
                WebApplication.Instance.ConnectionString = ConfigurationManager.ConnectionStrings[""ConnectionString""].ConnectionString;
            }
#if EASYTEST
            if(ConfigurationManager.ConnectionStrings[""EasyTestConnectionString""] != null) {
                WebApplication.Instance.ConnectionString = ConfigurationManager.ConnectionStrings[""EasyTestConnectionString""].ConnectionString;
            }
#endif
            if(System.Diagnostics.Debugger.IsAttached && WebApplication.Instance.CheckCompatibilityType == CheckCompatibilityType.DatabaseSchema) {
                WebApplication.Instance.DatabaseUpdateMode = DatabaseUpdateMode.UpdateDatabaseAlways;
            }
            WebApplication.Instance.Setup();
            WebApplication.Instance.Start();
        }
		//secur#6
		");
            
            #line 61 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\GlobalAsax.tt"
 if (HasSecurity){ 
            
            #line default
            #line hidden
            this.Write(@"		        private void MyApplication_LastLogonParametersRead(object sender, LastLogonParametersReadEventArgs e) {
              AuthenticationStandardLogonParameters logonParameters = e.LogonObject as AuthenticationStandardLogonParameters;
              if(logonParameters != null) {
                if(String.IsNullOrEmpty(logonParameters.UserName)) {
                    logonParameters.UserName = ""Admin"";
                }
              }
            }
");
            
            #line 70 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\GlobalAsax.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"        protected void Application_BeginRequest(Object sender, EventArgs e) {
        }
        protected void Application_EndRequest(Object sender, EventArgs e) {
        }
        protected void Application_AuthenticateRequest(Object sender, EventArgs e) {
        }
        protected void Application_Error(Object sender, EventArgs e) {
            ErrorHandling.Instance.ProcessApplicationError();
        }
        protected void Session_End(Object sender, EventArgs e) {
            WebApplication.LogOff(Session);
            WebApplication.DisposeInstance(Session);
        }
        protected void Application_End(Object sender, EventArgs e) {
        }
        #region Web Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
        }
        #endregion
    }
}
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
