// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleCsproj.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ModuleCsproj : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleCsproj.tt"
 FileName=@"\{0}.Module\{0}.Module.csproj"; 
            
            #line default
            #line hidden
            this.Write("\r\n<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/m" +
                    "sbuild/2003\" ToolsVersion=\"4.0\">\r\n\t<PropertyGroup>\r\n\t\t<Configuration Condition=\"" +
                    " \'$(Configuration)\' == \'\' \">Debug</Configuration>\r\n\t\t<Platform Condition=\" \'$(Pl" +
                    "atform)\' == \'\' \">AnyCPU</Platform>\r\n\t\t<ProductVersion>9.0.30729</ProductVersion>" +
                    "\r\n\t\t<SchemaVersion>2.0</SchemaVersion>\r\n\t\t<ProjectGuid>{5F15837D-D1E5-44DC-92F0-" +
                    "4F2EBE9C3F8D}</ProjectGuid>\r\n\t\t<OutputType>Library</OutputType>\r\n\t\t<AppDesignerF" +
                    "older>Properties</AppDesignerFolder>\r\n\t\t<RootNamespace>dxTestSolution.Module</Ro" +
                    "otNamespace>\r\n\t\t<AssemblyName>dxTestSolution.Module</AssemblyName>\r\n\t\t<TargetFra" +
                    "meworkVersion>v4.5.2</TargetFrameworkVersion>\r\n\t\t<FileUpgradeFlags>\r\n\t\t</FileUpg" +
                    "radeFlags>\r\n\t\t<UpgradeBackupLocation>\r\n\t\t</UpgradeBackupLocation>\r\n\t\t<OldToolsVe" +
                    "rsion>3.5</OldToolsVersion>\r\n\t\t<TargetFrameworkProfile />\r\n\t</PropertyGroup>\r\n\t<" +
                    "PropertyGroup Condition=\" \'$(Configuration)|$(Platform)\' == \'Debug|AnyCPU\' \">\r\n\t" +
                    "\t<DebugSymbols>true</DebugSymbols>\r\n\t\t<DebugType>full</DebugType>\r\n\t\t<Optimize>f" +
                    "alse</Optimize>\r\n\t\t<OutputPath>bin\\Debug\\</OutputPath>\r\n\t\t<DefineConstants>DEBUG" +
                    ";TRACE</DefineConstants>\r\n\t\t<ErrorReport>prompt</ErrorReport>\r\n\t\t<WarningLevel>4" +
                    "</WarningLevel>\r\n\t</PropertyGroup>\r\n\t<PropertyGroup Condition=\" \'$(Configuration" +
                    ")|$(Platform)\' == \'Release|AnyCPU\' \">\r\n\t\t<DebugType>pdbonly</DebugType>\r\n\t\t<Opti" +
                    "mize>true</Optimize>\r\n\t\t<OutputPath>bin\\Release\\</OutputPath>\r\n\t\t<DefineConstant" +
                    "s>TRACE</DefineConstants>\r\n\t\t<ErrorReport>prompt</ErrorReport>\r\n\t\t<WarningLevel>" +
                    "4</WarningLevel>\r\n\t</PropertyGroup>\r\n\t<PropertyGroup Condition=\" \'$(Configuratio" +
                    "n)|$(Platform)\' == \'EasyTest|AnyCPU\' \">\r\n\t\t<DebugSymbols>true</DebugSymbols>\r\n\t\t" +
                    "<OutputPath>bin\\EasyTest\\</OutputPath>\r\n\t\t<DefineConstants>TRACE;DEBUG;EASYTEST<" +
                    "/DefineConstants>\r\n\t\t<DebugType>full</DebugType>\r\n\t\t<PlatformTarget>AnyCPU</Plat" +
                    "formTarget>\r\n\t\t<ErrorReport>prompt</ErrorReport>\r\n\t</PropertyGroup>\r\n\t<ItemGroup" +
                    ">\r\n\t\t<Reference Include=\"DevExpress.Data.v20.1\">\r\n\t\t\t<SpecificVersion>False</Spe" +
                    "cificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress.ExpressApp.v20.1" +
                    "\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference In" +
                    "clude=\"DevExpress.ExpressApp.Xpo.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVer" +
                    "sion>\r\n\t\t\t<Private>False</Private>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExp" +
                    "ress.Persistent.Base.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</R" +
                    "eference>\r\n\t\t<Reference Include=\"DevExpress.Persistent.BaseImpl.v20.1\">\r\n\t\t\t<Spe" +
                    "cificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevE" +
                    "xpress.Printing.v20.1.Core\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</R" +
                    "eference>\r\n\t\t<Reference Include=\"DevExpress.Xpo.v20.1\">\r\n\t\t\t<SpecificVersion>Fal" +
                    "se</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t");
            
            #line 75 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleCsproj.tt"
 if (HasValidation){ 
            
            #line default
            #line hidden
            this.Write("\t\t<Reference Include=\"DevExpress.ExpressApp.Validation.v20.1>\r\n            <Speci" +
                    "ficVersion>False</SpecificVersion>\r\n        </Reference>\r\n\t\t");
            
            #line 79 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleCsproj.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 80 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleCsproj.tt"
 if (HasReports){ 
            
            #line default
            #line hidden
            this.Write(@"			<Reference Include=""DevExpress.ExpressApp.ReportsV2.v20.1"">
					<SpecificVersion>False</SpecificVersion>
				</Reference>
				<Reference Include=""DevExpress.Utils.v20.1"" >
					<SpecificVersion>False</SpecificVersion>
				</Reference>
				<Reference Include=""DevExpress.XtraReports.v20.1"" >
					<SpecificVersion>False</SpecificVersion>
				</Reference>
				<Reference Include=""DevExpress.XtraReports.v20.1.Extensions"" >
					<SpecificVersion>False</SpecificVersion>
				</Reference>
		");
            
            #line 93 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleCsproj.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 94 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleCsproj.tt"
 if (HasOffice){ 
            
            #line default
            #line hidden
            this.Write(@"					<Reference Include=""DevExpress.ExpressApp.Office.v20.1"" >
					<SpecificVersion>False</SpecificVersion>
				</Reference>
				<Reference Include=""DevExpress.Office.v20.1.Core"">
					<SpecificVersion>False</SpecificVersion>
				</Reference>
				<Reference Include=""DevExpress.RichEdit.v20.1.Core"">
					<SpecificVersion>False</SpecificVersion>
				</Reference>
				<Reference Include=""DevExpress.Spreadsheet.v20.1.Core"" >
					<SpecificVersion>False</SpecificVersion>
				</Reference>
</Reference>
		");
            
            #line 108 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleCsproj.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t\r\n\t\t\r\n\r\n\t\t<Reference Include=\"DevExpress.ExpressApp.Security.v20.1\">\r\n\t\t\t<S" +
                    "pecificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"De" +
                    "vExpress.ExpressApp.Security.Xpo.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVer" +
                    "sion>\r\n\t\t\t<Private>False</Private>\r\n\t\t</Reference>\r\n\r\n\r\n\t\t<Reference Include=\"De" +
                    "vExpress.RichEdit.v20.1.Export\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t" +
                    "\t</Reference>\r\n\t\t<Reference Include=\"System\">\r\n\t\t\t<Name>System</Name>\r\n\t\t\t<Priva" +
                    "te>False</Private>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"System.Data\">\r\n\t\t\t<Nam" +
                    "e>System.Data</Name>\r\n\t\t\t<Private>False</Private>\r\n\t\t</Reference>\r\n\t\t<Reference " +
                    "Include=\"System.Drawing\">\r\n\t\t\t<Private>False</Private>\r\n\t\t</Reference>\r\n\t\t<Refer" +
                    "ence Include=\"System.Xml\">\r\n\t\t\t<Name>System.XML</Name>\r\n\t\t\t<Private>False</Priva" +
                    "te>\r\n\t\t</Reference>\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<Compile Include=\"BusinessOb" +
                    "jects\\Contact.cs\" />\r\n\t\t<Compile Include=\"BusinessObjects\\MyTask.cs\" />\r\n\t\t<Comp" +
                    "ile Include=\"BusinessObjects\\CustomClass.cs\" />\r\n\t\t<!--//report#15-->\r\n\t\t<Compil" +
                    "e Include=\"Controllers\\CustomControllers.cs\">\r\n\t\t\t<SubType>Component</SubType>\r\n" +
                    "\t\t</Compile>\r\n\t\t<Compile Include=\"DatabaseUpdate\\Updater.cs\" />\r\n\t\t<Compile Incl" +
                    "ude=\"Module.cs\">\r\n\t\t\t<SubType>Component</SubType>\r\n\t\t</Compile>\r\n\t\t<Compile Incl" +
                    "ude=\"Module.Designer.cs\">\r\n\t\t\t<DependentUpon>Module.cs</DependentUpon>\r\n\t\t</Comp" +
                    "ile>\r\n\t\t<Compile Include=\"Properties\\AssemblyInfo.cs\" />\r\n\t</ItemGroup>\r\n\t<ItemG" +
                    "roup>\r\n\t\t<EmbeddedResource Include=\"Model.DesignedDiffs.xafml\" />\r\n\t\t<EmbeddedRe" +
                    "source Include=\"Module.resx\">\r\n\t\t\t<SubType>Designer</SubType>\r\n\t\t\t<DependentUpon" +
                    ">Module.cs</DependentUpon>\r\n\t\t</EmbeddedResource>\r\n\t\t<EmbeddedResource Include=\"" +
                    "Properties\\licenses.licx\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Data" +
                    "baseUpdate\\ReadMe.txt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Busines" +
                    "sObjects\\ReadMe.txt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Controlle" +
                    "rs\\ReadMe.txt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"FunctionalTests" +
                    "\\ReadMe.txt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"FunctionalTests\\s" +
                    "ample.ets\" />\r\n\t\t<None Include=\"FunctionalTests\\WebSample.ets\" />\r\n\t\t<None Inclu" +
                    "de=\"Images\\ReadMe.txt\" />\r\n\t\t<None Include=\"ReadMe.txt\" />\r\n\t</ItemGroup>\r\n\t<Ite" +
                    "mGroup>\r\n\t\t<None Include=\"FunctionalTests\\config.xml\">\r\n\t\t\t<SubType>Designer</Su" +
                    "bType>\r\n\t\t</None>\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<Content Include=\"Welcome.html" +
                    "\" />\r\n\t</ItemGroup>\r\n\t<Import Project=\"$(MSBuildBinPath)\\Microsoft.CSharp.target" +
                    "s\" />\r\n\t<!-- To modify your build process, add your task inside one of the targe" +
                    "ts below and uncomment it. \r\n       Other similar extension points exist, see Mi" +
                    "crosoft.Common.targets.\r\n  <Target Name=\"BeforeBuild\">\r\n  </Target>\r\n  <Target N" +
                    "ame=\"AfterBuild\">\r\n  </Target>\r\n  -->\r\n</Project>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
