// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ModuleWinCsproj : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 FileName=@"\{0}.Module.Win\{0}.Module.Win.csproj"; 
            
            #line default
            #line hidden
            this.Write("\r\n<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/m" +
                    "sbuild/2003\" ToolsVersion=\"4.0\">\r\n\t<PropertyGroup>\r\n\t\t<Configuration Condition=\"" +
                    " \'$(Configuration)\' == \'\' \">Debug</Configuration>\r\n\t\t<Platform Condition=\" \'$(Pl" +
                    "atform)\' == \'\' \">AnyCPU</Platform>\r\n\t\t<ProductVersion>9.0.30729</ProductVersion>" +
                    "\r\n\t\t<SchemaVersion>2.0</SchemaVersion>\r\n\t\t<ProjectGuid>{7964F87D-BC5D-4C4E-8B2F-" +
                    "71E89739AA97}</ProjectGuid>\r\n\t\t<OutputType>Library</OutputType>\r\n\t\t<AppDesignerF" +
                    "older>Properties</AppDesignerFolder>\r\n\t\t<RootNamespace>dxTestSolution.Module.Win" +
                    "</RootNamespace>\r\n\t\t<AssemblyName>dxTestSolution.Module.Win</AssemblyName>\r\n\t\t<T" +
                    "argetFrameworkVersion>v4.5.2</TargetFrameworkVersion>\r\n\t\t<FileUpgradeFlags>\r\n\t\t<" +
                    "/FileUpgradeFlags>\r\n\t\t<UpgradeBackupLocation>\r\n\t\t</UpgradeBackupLocation>\r\n\t\t<Ol" +
                    "dToolsVersion>3.5</OldToolsVersion>\r\n\t\t<TargetFrameworkProfile />\r\n\t\t<PublishUrl" +
                    ">publish\\</PublishUrl>\r\n\t\t<Install>true</Install>\r\n\t\t<InstallFrom>Disk</InstallF" +
                    "rom>\r\n\t\t<UpdateEnabled>false</UpdateEnabled>\r\n\t\t<UpdateMode>Foreground</UpdateMo" +
                    "de>\r\n\t\t<UpdateInterval>7</UpdateInterval>\r\n\t\t<UpdateIntervalUnits>Days</UpdateIn" +
                    "tervalUnits>\r\n\t\t<UpdatePeriodically>false</UpdatePeriodically>\r\n\t\t<UpdateRequire" +
                    "d>false</UpdateRequired>\r\n\t\t<MapFileExtensions>true</MapFileExtensions>\r\n\t\t<Appl" +
                    "icationRevision>0</ApplicationRevision>\r\n\t\t<ApplicationVersion>1.0.0.%2a</Applic" +
                    "ationVersion>\r\n\t\t<IsWebBootstrapper>false</IsWebBootstrapper>\r\n\t\t<UseApplication" +
                    "Trust>false</UseApplicationTrust>\r\n\t\t<BootstrapperEnabled>true</BootstrapperEnab" +
                    "led>\r\n\t</PropertyGroup>\r\n\t<PropertyGroup Condition=\" \'$(Configuration)|$(Platfor" +
                    "m)\' == \'Debug|AnyCPU\' \">\r\n\t\t<DebugSymbols>true</DebugSymbols>\r\n\t\t<DebugType>full" +
                    "</DebugType>\r\n\t\t<Optimize>false</Optimize>\r\n\t\t<OutputPath>bin\\Debug\\</OutputPath" +
                    ">\r\n\t\t<DefineConstants>DEBUG;TRACE</DefineConstants>\r\n\t\t<ErrorReport>prompt</Erro" +
                    "rReport>\r\n\t\t<WarningLevel>4</WarningLevel>\r\n\t</PropertyGroup>\r\n\t<PropertyGroup C" +
                    "ondition=\" \'$(Configuration)|$(Platform)\' == \'Release|AnyCPU\' \">\r\n\t\t<DebugType>p" +
                    "dbonly</DebugType>\r\n\t\t<Optimize>true</Optimize>\r\n\t\t<OutputPath>bin\\Release\\</Out" +
                    "putPath>\r\n\t\t<DefineConstants>TRACE</DefineConstants>\r\n\t\t<ErrorReport>prompt</Err" +
                    "orReport>\r\n\t\t<WarningLevel>4</WarningLevel>\r\n\t</PropertyGroup>\r\n\t<PropertyGroup " +
                    "Condition=\" \'$(Configuration)|$(Platform)\' == \'EasyTest|AnyCPU\' \">\r\n\t\t<DebugSymb" +
                    "ols>true</DebugSymbols>\r\n\t\t<OutputPath>bin\\EasyTest\\</OutputPath>\r\n\t\t<DefineCons" +
                    "tants>TRACE;DEBUG;EASYTEST</DefineConstants>\r\n\t\t<DebugType>full</DebugType>\r\n\t\t<" +
                    "PlatformTarget>AnyCPU</PlatformTarget>\r\n\t\t<ErrorReport>prompt</ErrorReport>\r\n\t</" +
                    "PropertyGroup>\r\n\t<ItemGroup>\r\n\t\t<Reference Include=\"DevExpress.Data.v20.1\">\r\n\t\t\t" +
                    "<SpecificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"" +
                    "DevExpress.ExpressApp.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</" +
                    "Reference>\r\n\t\t<Reference Include=\"DevExpress.ExpressApp.Win.v20.1\">\r\n\t\t\t<Specifi" +
                    "cVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpre" +
                    "ss.ExpressApp.Xpo.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</Refe" +
                    "rence>\r\n\t\t<Reference Include=\"DevExpress.Persistent.Base.v20.1\">\r\n\t\t\t<SpecificVe" +
                    "rsion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress." +
                    "Persistent.BaseImpl.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</Re" +
                    "ference>\r\n\t\t<Reference Include=\"DevExpress.Printing.v20.1.Core\">\r\n\t\t\t<SpecificVe" +
                    "rsion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress." +
                    "Data.Desktop.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</Reference" +
                    ">\r\n\t\t<Reference Include=\"DevExpress.Utils.v20.1\">\r\n\t\t\t<SpecificVersion>False</Sp" +
                    "ecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress.Xpo.v20.1\">\r\n\t\t" +
                    "\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=" +
                    "\"DevExpress.XtraBars.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</R" +
                    "eference>\r\n\t\t<Reference Include=\"DevExpress.XtraEditors.v20.1\">\r\n\t\t\t<SpecificVer" +
                    "sion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress.X" +
                    "traGrid.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t" +
                    "<Reference Include=\"DevExpress.XtraLayout.v20.1\">\r\n\t\t\t<SpecificVersion>False</Sp" +
                    "ecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress.XtraNavBar.v20." +
                    "1\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference I" +
                    "nclude=\"DevExpress.XtraPrinting.v20.1\">\r\n\t\t\t<SpecificVersion>False</SpecificVers" +
                    "ion>\r\n\t\t</Reference>\r\n\t\t");
            
            #line 116 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 if (HasValidation){ 
            
            #line default
            #line hidden
            this.Write(@"		<Reference Include=""DevExpress.XtraSpreadsheet.v20.1"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
		<Reference Include=""DevExpress.ExpressApp.Validation.v20.1"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
		<Reference Include=""DevExpress.ExpressApp.Validation.Win.v20.1"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
");
            
            #line 126 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 } 
            
            #line default
            #line hidden
            
            #line 127 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 if (HasOffice){ 
            
            #line default
            #line hidden
            this.Write(@"		<Reference Include=""DevExpress.ExpressApp.Office.v20.1"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.ExpressApp.Office.Win.v20.1"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.Office.v20.1.Core"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.RichEdit.v20.1.Core"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.Spreadsheet.v20.1.Core"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.XtraRichEdit.v20.1"" >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.XtraSpreadsheet.v20.1""ы >
			<SpecificVersion>False</SpecificVersion>
		</Reference>
				<Reference Include=""DevExpress.Office.v20.1.Core"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
		<Reference Include=""DevExpress.RichEdit.v20.1.Core"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
		<Reference Include=""DevExpress.RichEdit.v20.1.Export"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
");
            
            #line 158 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 } 
            
            #line default
            #line hidden
            
            #line 159 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 if (HasReports){ 
            
            #line default
            #line hidden
            this.Write("\t<Reference Include=\"DevExpress.ExpressApp.ReportsV2.v20.1\" >\r\n\t\t\t<SpecificVersio" +
                    "n>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress.Expr" +
                    "essApp.ReportsV2.Win.v20.1\" >\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</" +
                    "Reference>\r\n");
            
            #line 166 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"

	


		<Reference Include=""System"">
			<Name>System</Name>
			<Private>False</Private>
		</Reference>
		<Reference Include=""System.configuration"">
			<Private>False</Private>
		</Reference>
		<Reference Include=""System.Data"">
			<Name>System.Data</Name>
			<Private>False</Private>
		</Reference>
		<Reference Include=""System.Drawing"">
			<Name>System.Drawing</Name>
			<Private>False</Private>
		</Reference>
		<Reference Include=""System.Windows.Forms"">
			<Name>System.Windows.Forms</Name>
			<Private>False</Private>
		</Reference>
		<Reference Include=""System.Xml"">
			<Name>System.XML</Name>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		");
            
            #line 197 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 if (HasOffice){ 
            
            #line default
            #line hidden
            this.Write("\t\t<Compile Include=\"Controllers\\ClearMailMergeCacheController.cs\">\r\n  <SubType>Co" +
                    "mponent</SubType>\r\n</Compile>\r\n");
            
            #line 201 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWinCsproj.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t<Compile Include=\"Controllers\\CustomWinController.cs\">\r\n\t\t\t<SubType>Component</" +
                    "SubType>\r\n\t\t</Compile>\r\n\t\t<Compile Include=\"WinModule.cs\">\r\n\t\t\t<SubType>Componen" +
                    "t</SubType>\r\n\t\t</Compile>\r\n\t\t<Compile Include=\"Properties\\AssemblyInfo.cs\" />\r\n\t" +
                    "\t<Compile Include=\"WinModule.Designer.cs\">\r\n\t\t\t<DependentUpon>WinModule.cs</Depe" +
                    "ndentUpon>\r\n\t\t</Compile>\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<EmbeddedResource Inclu" +
                    "de=\"Model.DesignedDiffs.xafml\" />\r\n\t\t<EmbeddedResource Include=\"WinModule.resx\">" +
                    "\r\n\t\t\t<DependentUpon>WinModule.cs</DependentUpon>\r\n\t\t\t<SubType>Designer</SubType>" +
                    "\r\n\t\t</EmbeddedResource>\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<ProjectReference Includ" +
                    "e=\"..\\dxTestSolution.Module\\dxTestSolution.Module.csproj\">\r\n\t\t\t<Project>{5F15837" +
                    "D-D1E5-44DC-92F0-4F2EBE9C3F8D}</Project>\r\n\t\t\t<Name>dxTestSolution.Module</Name>\r" +
                    "\n\t\t</ProjectReference>\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Controller" +
                    "s\\ReadMe.txt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Editors\\ReadMe.t" +
                    "xt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Images\\ReadMe.txt\" />\r\n\t\t<" +
                    "None Include=\"ReadMe.txt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<BootstrapperPackag" +
                    "e Include=\"Microsoft.Net.Client.3.5\">\r\n\t\t\t<Visible>False</Visible>\r\n\t\t\t<ProductN" +
                    "ame>.NET Framework 3.5 SP1 Client Profile</ProductName>\r\n\t\t\t<Install>false</Inst" +
                    "all>\r\n\t\t</BootstrapperPackage>\r\n\t\t<BootstrapperPackage Include=\"Microsoft.Net.Fr" +
                    "amework.3.5.SP1\">\r\n\t\t\t<Visible>False</Visible>\r\n\t\t\t<ProductName>.NET Framework 3" +
                    ".5 SP1</ProductName>\r\n\t\t\t<Install>true</Install>\r\n\t\t</BootstrapperPackage>\r\n\t\t<B" +
                    "ootstrapperPackage Include=\"Microsoft.Windows.Installer.3.1\">\r\n\t\t\t<Visible>False" +
                    "</Visible>\r\n\t\t\t<ProductName>Windows Installer 3.1</ProductName>\r\n\t\t\t<Install>tru" +
                    "e</Install>\r\n\t\t</BootstrapperPackage>\r\n\t</ItemGroup>\r\n\t<Import Project=\"$(MSBuil" +
                    "dBinPath)\\Microsoft.CSharp.targets\" />\r\n\t<!-- To modify your build process, add " +
                    "your task inside one of the targets below and uncomment it. \r\n       Other simil" +
                    "ar extension points exist, see Microsoft.Common.targets.\r\n  <Target Name=\"Before" +
                    "Build\">\r\n  </Target>\r\n  <Target Name=\"AfterBuild\">\r\n  </Target>\r\n  -->\r\n</Projec" +
                    "t>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
