// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleDesigner.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ModuleDesigner : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleDesigner.tt"
 FileName=@"\{0}.Module\Module.Designer.cs"; 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace dxTestSolution.Module {\r\n\tpartial class dxTestSolutionModule {\r\n\t\t///" +
                    " <summary> \r\n\t\t/// Required designer variable.\r\n\t\t/// </summary>\r\n\t\tprivate Syst" +
                    "em.ComponentModel.IContainer components = null;\r\n\r\n\t\t/// <summary> \r\n\t\t/// Clean" +
                    " up any resources being used.\r\n\t\t/// </summary>\r\n\t\t/// <param name=\"disposing\">t" +
                    "rue if managed resources should be disposed; otherwise, false.</param>\r\n\t\tprotec" +
                    "ted override void Dispose(bool disposing) {\r\n\t\t\tif(disposing && (components != n" +
                    "ull)) {\r\n\t\t\t\tcomponents.Dispose();\r\n\t\t\t}\r\n\t\t\tbase.Dispose(disposing);\r\n\t\t}\r\n\r\n\t\t" +
                    "#region Component Designer generated code\r\n\r\n\t\t/// <summary> \r\n\t\t/// Required me" +
                    "thod for Designer support - do not modify \r\n\t\t/// the contents of this method wi" +
                    "th the code editor.\r\n\t\t/// </summary>\r\n\t\tprivate void InitializeComponent() {\r\n\t" +
                    "\t\t// \r\n\t\t\t// dxTestSolutionModule\r\n\t\t\t// \r\n\t\t\tthis.AdditionalExportedTypes.Add(t" +
                    "ypeof(DevExpress.Persistent.BaseImpl.ModelDifference));\r\n            this.Additi" +
                    "onalExportedTypes.Add(typeof(DevExpress.Persistent.BaseImpl.BaseObject));\r\n     " +
                    "       this.AdditionalExportedTypes.Add(typeof(DevExpress.Xpo.XPCustomObject));\r" +
                    "\n            this.AdditionalExportedTypes.Add(typeof(DevExpress.Xpo.XPBaseObject" +
                    "));\r\n            this.AdditionalExportedTypes.Add(typeof(DevExpress.Xpo.Persiste" +
                    "ntBase));\r\n            this.AdditionalExportedTypes.Add(typeof(DevExpress.Persis" +
                    "tent.BaseImpl.ModelDifferenceAspect));\r\n            \r\n\t\t\tthis.RequiredModuleType" +
                    "s.Add(typeof(DevExpress.ExpressApp.SystemModule.SystemModule));\r\n\t\t\t");
            
            #line 44 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleDesigner.tt"
 if (HasReports){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tthis.RequiredModuleTypes.Add(typeof(DevExpress.ExpressApp.ReportsV2.ReportsMod" +
                    "uleV2));\r\n\t        ");
            
            #line 46 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 47 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleDesigner.tt"
 if (HasOffice){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t this.RequiredModuleTypes.Add(typeof(DevExpress.ExpressApp.Office.OfficeModule" +
                    "));\r\n\t\t\t ");
            
            #line 49 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleDesigner.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\t#endregion\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
