// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "c:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWebCsproj.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ModuleWebCsproj : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "c:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWebCsproj.tt"
 FileName=@"\{0}.Module.Web\{0}.Module.Web.csproj"; 
            
            #line default
            #line hidden
            this.Write("\r\n<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/m" +
                    "sbuild/2003\" ToolsVersion=\"4.0\">\r\n\t<PropertyGroup>\r\n\t\t<Configuration Condition=\"" +
                    " \'$(Configuration)\' == \'\' \">Debug</Configuration>\r\n\t\t<Platform Condition=\" \'$(Pl" +
                    "atform)\' == \'\' \">AnyCPU</Platform>\r\n\t\t<ProductVersion>9.0.30729</ProductVersion>" +
                    "\r\n\t\t<SchemaVersion>2.0</SchemaVersion>\r\n\t\t<ProjectGuid>{0C729AAD-7626-4668-A7F1-" +
                    "35F7D240489D}</ProjectGuid>\r\n\t\t<OutputType>Library</OutputType>\r\n\t\t<AppDesignerF" +
                    "older>Properties</AppDesignerFolder>\r\n\t\t<RootNamespace>dxTestSolution.Module.Web" +
                    "</RootNamespace>\r\n\t\t<AssemblyName>dxTestSolution.Module.Web</AssemblyName>\r\n\t\t<T" +
                    "argetFrameworkVersion>v4.5.2</TargetFrameworkVersion>\r\n\t\t<FileUpgradeFlags>\r\n\t\t<" +
                    "/FileUpgradeFlags>\r\n\t\t<UpgradeBackupLocation>\r\n\t\t</UpgradeBackupLocation>\r\n\t\t<Ol" +
                    "dToolsVersion>3.5</OldToolsVersion>\r\n\t\t<TargetFrameworkProfile />\r\n\t\t<PublishUrl" +
                    ">publish\\</PublishUrl>\r\n\t\t<Install>true</Install>\r\n\t\t<InstallFrom>Disk</InstallF" +
                    "rom>\r\n\t\t<UpdateEnabled>false</UpdateEnabled>\r\n\t\t<UpdateMode>Foreground</UpdateMo" +
                    "de>\r\n\t\t<UpdateInterval>7</UpdateInterval>\r\n\t\t<UpdateIntervalUnits>Days</UpdateIn" +
                    "tervalUnits>\r\n\t\t<UpdatePeriodically>false</UpdatePeriodically>\r\n\t\t<UpdateRequire" +
                    "d>false</UpdateRequired>\r\n\t\t<MapFileExtensions>true</MapFileExtensions>\r\n\t\t<Appl" +
                    "icationRevision>0</ApplicationRevision>\r\n\t\t<ApplicationVersion>1.0.0.%2a</Applic" +
                    "ationVersion>\r\n\t\t<IsWebBootstrapper>false</IsWebBootstrapper>\r\n\t\t<UseApplication" +
                    "Trust>false</UseApplicationTrust>\r\n\t\t<BootstrapperEnabled>true</BootstrapperEnab" +
                    "led>\r\n\t</PropertyGroup>\r\n\t<PropertyGroup Condition=\" \'$(Configuration)|$(Platfor" +
                    "m)\' == \'Debug|AnyCPU\' \">\r\n\t\t<DebugSymbols>true</DebugSymbols>\r\n\t\t<DebugType>full" +
                    "</DebugType>\r\n\t\t<Optimize>false</Optimize>\r\n\t\t<OutputPath>bin\\Debug\\</OutputPath" +
                    ">\r\n\t\t<DefineConstants>DEBUG;TRACE</DefineConstants>\r\n\t\t<ErrorReport>prompt</Erro" +
                    "rReport>\r\n\t\t<WarningLevel>4</WarningLevel>\r\n\t</PropertyGroup>\r\n\t<PropertyGroup C" +
                    "ondition=\" \'$(Configuration)|$(Platform)\' == \'Release|AnyCPU\' \">\r\n\t\t<DebugType>p" +
                    "dbonly</DebugType>\r\n\t\t<Optimize>true</Optimize>\r\n\t\t<OutputPath>bin\\Release\\</Out" +
                    "putPath>\r\n\t\t<DefineConstants>TRACE</DefineConstants>\r\n\t\t<ErrorReport>prompt</Err" +
                    "orReport>\r\n\t\t<WarningLevel>4</WarningLevel>\r\n\t</PropertyGroup>\r\n\t<PropertyGroup " +
                    "Condition=\" \'$(Configuration)|$(Platform)\' == \'EasyTest|AnyCPU\' \">\r\n\t\t<DebugSymb" +
                    "ols>true</DebugSymbols>\r\n\t\t<OutputPath>bin\\EasyTest\\</OutputPath>\r\n\t\t<DefineCons" +
                    "tants>TRACE;DEBUG;EASYTEST</DefineConstants>\r\n\t\t<DebugType>full</DebugType>\r\n\t\t<" +
                    "PlatformTarget>AnyCPU</PlatformTarget>\r\n\t\t<ErrorReport>prompt</ErrorReport>\r\n\t</" +
                    "PropertyGroup>\r\n\t<ItemGroup>\r\n\t\t<Reference Include=\"DevExpress.Data.v21.2\">\r\n\t\t\t" +
                    "<SpecificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"" +
                    "DevExpress.ExpressApp.v21.2\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</" +
                    "Reference>\r\n\r\n\t\t<Reference Include=\"DevExpress.ExpressApp.Web.v21.2\">\r\n\t\t\t<Speci" +
                    "ficVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExp" +
                    "ress.ExpressApp.Xpo.v21.2\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t</Re" +
                    "ference>\r\n\t\t<Reference Include=\"DevExpress.Persistent.Base.v21.2\">\r\n\t\t\t<Specific" +
                    "Version>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpres" +
                    "s.Persistent.BaseImpl.Xpo.v21.2\">\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n" +
                    "\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress.Printing.v21.2.Core\">\r\n\t\t\t<Spec" +
                    "ificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\r\n\t\t");
            
            #line 91 "c:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWebCsproj.tt"
 if (HasValidation){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<Reference Include=\"DevExpress.ExpressApp.Validation.v21.2\">\r\n  <SpecificVers" +
                    "ion>False</SpecificVersion>\r\n</Reference>\r\n\t\t<Reference Include=\"DevExpress.Expr" +
                    "essApp.Validation.Web.v21.2\">\r\n  <SpecificVersion>False</SpecificVersion>\r\n</Ref" +
                    "erence>\r\n");
            
            #line 98 "c:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWebCsproj.tt"
 } 
            
            #line default
            #line hidden
            
            #line 99 "c:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWebCsproj.tt"
 if (HasOffice){ 
            
            #line default
            #line hidden
            this.Write(@"		<Reference Include=""DevExpress.ExpressApp.Office.v21.2"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.ExpressApp.Office.Web.v21.2"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.RichEdit.v21.2.Core"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.Spreadsheet.v21.2.Core"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.Web.ASPxRichEdit.v21.2"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
<Reference Include=""DevExpress.Web.ASPxSpreadsheet.v21.2"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
		<Reference Include=""DevExpress.RichEdit.v21.2.Export"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>

		<Reference Include=""DevExpress.Office.v21.2.Core"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
		<Reference Include=""DevExpress.RichEdit.v21.2.Core"">
			<SpecificVersion>False</SpecificVersion>
		</Reference>
");
            
            #line 128 "c:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWebCsproj.tt"
 } 
            
            #line default
            #line hidden
            
            #line 129 "c:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWebCsproj.tt"
 if (HasReports){ 
            
            #line default
            #line hidden
            this.Write("\t\t<Reference Include=\"DevExpress.ExpressApp.ReportsV2.v21.2\" >\r\n\t\t\t<SpecificVersi" +
                    "on>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress.Exp" +
                    "ressApp.ReportsV2.Web.v21.2\" >\r\n\t\t\t<SpecificVersion>False</SpecificVersion>\r\n\t\t<" +
                    "/Reference>\r\n");
            
            #line 136 "c:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\ModuleWebCsproj.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t<Reference Include=\"DevExpress.Web.v21.2\">\r\n\t\t\t<SpecificVersion>False</Speci" +
                    "ficVersion>\r\n\t\t</Reference>\r\n\t\t<Reference Include=\"DevExpress.Xpo.v21.2\">\r\n\t\t\t<S" +
                    "pecificVersion>False</SpecificVersion>\r\n\t\t</Reference>\r\n\t\t\r\n\t\t\r\n\t\t<Reference Inc" +
                    "lude=\"System\">\r\n\t\t\t<Private>False</Private>\r\n\t\t</Reference>\r\n\t\t<Reference Includ" +
                    "e=\"System.Data\">\r\n\t\t\t<Private>False</Private>\r\n\t\t</Reference>\r\n\t\t<Reference Incl" +
                    "ude=\"System.Drawing\" />\r\n\t\t<Reference Include=\"System.Web\" />\r\n\t\t<Reference Incl" +
                    "ude=\"System.Xml\">\r\n\t\t\t<Private>False</Private>\r\n\t\t</Reference>\r\n\t</ItemGroup>\r\n\t" +
                    "<ItemGroup>\r\n\t\t<Compile Include=\"Controllers\\CustomWebController.cs\">\r\n\t\t\t<SubTy" +
                    "pe>Component</SubType>\r\n\t\t</Compile>\r\n\t\t<Compile Include=\"WebModule.cs\">\r\n\t\t\t<Su" +
                    "bType>Component</SubType>\r\n\t\t</Compile>\r\n\t\t<Compile Include=\"Properties\\Assembly" +
                    "Info.cs\" />\r\n\t\t<Compile Include=\"WebModule.Designer.cs\">\r\n\t\t\t<DependentUpon>WebM" +
                    "odule.cs</DependentUpon>\r\n\t\t</Compile>\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<Embedded" +
                    "Resource Include=\"Model.DesignedDiffs.xafml\" />\r\n\t\t<EmbeddedResource Include=\"Pr" +
                    "operties\\licenses.licx\" />\r\n\t\t<EmbeddedResource Include=\"WebModule.resx\">\r\n\t\t\t<D" +
                    "ependentUpon>WebModule.cs</DependentUpon>\r\n\t\t\t<SubType>Designer</SubType>\r\n\t\t</E" +
                    "mbeddedResource>\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<ProjectReference Include=\"..\\d" +
                    "xTestSolution.Module\\dxTestSolution.Module.csproj\">\r\n\t\t\t<Project>{5F15837D-D1E5-" +
                    "44DC-92F0-4F2EBE9C3F8D}</Project>\r\n\t\t\t<Name>dxTestSolution.Module</Name>\r\n\t\t</Pr" +
                    "ojectReference>\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Controllers\\ReadM" +
                    "e.txt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Editors\\ReadMe.txt\" />\r" +
                    "\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<None Include=\"Images\\ReadMe.txt\" />\r\n\t\t<None In" +
                    "clude=\"ReadMe.txt\" />\r\n\t</ItemGroup>\r\n\t<ItemGroup>\r\n\t\t<BootstrapperPackage Inclu" +
                    "de=\"Microsoft.Net.Client.3.5\">\r\n\t\t\t<Visible>False</Visible>\r\n\t\t\t<ProductName>.NE" +
                    "T Framework 3.5 SP1 Client Profile</ProductName>\r\n\t\t\t<Install>false</Install>\r\n\t" +
                    "\t</BootstrapperPackage>\r\n\t\t<BootstrapperPackage Include=\"Microsoft.Net.Framework" +
                    ".3.5.SP1\">\r\n\t\t\t<Visible>False</Visible>\r\n\t\t\t<ProductName>.NET Framework 3.5 SP1<" +
                    "/ProductName>\r\n\t\t\t<Install>true</Install>\r\n\t\t</BootstrapperPackage>\r\n\t\t<Bootstra" +
                    "pperPackage Include=\"Microsoft.Windows.Installer.3.1\">\r\n\t\t\t<Visible>False</Visib" +
                    "le>\r\n\t\t\t<ProductName>Windows Installer 3.1</ProductName>\r\n\t\t\t<Install>true</Inst" +
                    "all>\r\n\t\t</BootstrapperPackage>\r\n\t</ItemGroup>\r\n\t<Import Project=\"$(MSBuildBinPat" +
                    "h)\\Microsoft.CSharp.targets\" />\r\n\t<!-- To modify your build process, add your ta" +
                    "sk inside one of the targets below and uncomment it. \r\n       Other similar exte" +
                    "nsion points exist, see Microsoft.Common.targets.\r\n  <Target Name=\"BeforeBuild\">" +
                    "\r\n  </Target>\r\n  <Target Name=\"AfterBuild\">\r\n  </Target>\r\n  -->\r\n</Project>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
