// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class WebCsproj : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 FileName=@"\{0}.Web\{0}.Web.csproj"; 
            
            #line default
            #line hidden
            this.Write("\r\n<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/m" +
                    "sbuild/2003\" ToolsVersion=\"4.0\">\r\n  <Import Project=\"$(MSBuildExtensionsPath)\\$(" +
                    "MSBuildToolsVersion)\\Microsoft.Common.props\" Condition=\"Exists(\'$(MSBuildExtensi" +
                    "onsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props\')\" />\r\n  <PropertyGroup>\r" +
                    "\n    <Configuration Condition=\" \'$(Configuration)\' == \'\' \">Debug</Configuration>" +
                    "\r\n    <Platform Condition=\" \'$(Platform)\' == \'\' \">AnyCPU</Platform>\r\n    <Produc" +
                    "tVersion>9.0.30729</ProductVersion>\r\n    <SchemaVersion>2.0</SchemaVersion>\r\n   " +
                    " <ProjectGuid>{82A6DBC9-B1B4-44E4-9718-55DF930CD349}</ProjectGuid>\r\n    <Project" +
                    "TypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f" +
                    "79efbc}</ProjectTypeGuids>\r\n    <OutputType>Library</OutputType>\r\n    <AppDesign" +
                    "erFolder>Properties</AppDesignerFolder>\r\n    <RootNamespace>dxTestSolution.Web</" +
                    "RootNamespace>\r\n    <AssemblyName>dxTestSolution.Web</AssemblyName>\r\n    <Target" +
                    "FrameworkVersion>v4.5.2</TargetFrameworkVersion>\r\n    <FileUpgradeFlags>\r\n    </" +
                    "FileUpgradeFlags>\r\n    <OldToolsVersion>3.5</OldToolsVersion>\r\n    <UpgradeBacku" +
                    "pLocation>\r\n    </UpgradeBackupLocation>\r\n    <TargetFrameworkProfile />\r\n    <U" +
                    "seIISExpress>true</UseIISExpress>\r\n    <IISExpressSSLPort>44300</IISExpressSSLPo" +
                    "rt>\r\n    <IISExpressAnonymousAuthentication>enabled</IISExpressAnonymousAuthenti" +
                    "cation>\r\n    <IISExpressWindowsAuthentication>disabled</IISExpressWindowsAuthent" +
                    "ication>\r\n    <IISExpressUseClassicPipelineMode>false</IISExpressUseClassicPipel" +
                    "ineMode>\r\n    <UseGlobalApplicationHostFile />\r\n  </PropertyGroup>\r\n  <PropertyG" +
                    "roup Condition=\" \'$(Configuration)|$(Platform)\' == \'Debug|AnyCPU\' \">\r\n    <Debug" +
                    "Symbols>true</DebugSymbols>\r\n    <DebugType>full</DebugType>\r\n    <Optimize>fals" +
                    "e</Optimize>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstants>DEBUG;TRAC" +
                    "E</DefineConstants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4<" +
                    "/WarningLevel>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'$(Configuratio" +
                    "n)|$(Platform)\' == \'Release|AnyCPU\' \">\r\n    <DebugType>pdbonly</DebugType>\r\n    " +
                    "<Optimize>true</Optimize>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstan" +
                    "ts>TRACE</DefineConstants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningL" +
                    "evel>4</WarningLevel>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'$(Confi" +
                    "guration)|$(Platform)\' == \'EasyTest|AnyCPU\' \">\r\n    <DebugSymbols>true</DebugSym" +
                    "bols>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstants>TRACE;DEBUG;EASYT" +
                    "EST</DefineConstants>\r\n    <DebugType>full</DebugType>\r\n    <PlatformTarget>AnyC" +
                    "PU</PlatformTarget>\r\n    <ErrorReport>prompt</ErrorReport>\r\n  </PropertyGroup>\r\n" +
                    "  <ItemGroup>\r\n\r\n\t  <Reference Include=\"DevExpress.DataAccess.v21.2\">\r\n      <Sp" +
                    "ecificVersion>False</SpecificVersion>\r\n    </Reference>\r\n");
            
            #line 65 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 if (HasReports){ 
            
            #line default
            #line hidden
            this.Write(@" <Reference Include=""DevExpress.ExpressApp.ReportsV2.v21.2"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.ExpressApp.ReportsV2.Web.v21.2"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.XtraReports.v21.2"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.XtraReports.v21.2.Extensions"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.XtraReports.v21.2.Web"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
");
            
            #line 81 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 } 
            
            #line default
            #line hidden
            
            #line 82 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 if (HasOffice){ 
            
            #line default
            #line hidden
            this.Write(@"    <Reference Include=""DevExpress.Office.v21.2.Core"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include=""DevExpress.RichEdit.v21.2.Core"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
	    <Reference Include=""DevExpress.RichEdit.v21.2.Export"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>

		 <Reference Include=""DevExpress.ExpressApp.Office.v21.2"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.ExpressApp.Office.Web.v21.2"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.RichEdit.v21.2.Core"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.Spreadsheet.v21.2.Core"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.Web.ASPxRichEdit.v21.2"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.Web.ASPxSpreadsheet.v21.2"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
");
            
            #line 111 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 } 
            
            #line default
            #line hidden
            
            #line 112 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 if (HasSecurity){ 
            
            #line default
            #line hidden
            this.Write(@"    <Reference Include=""DevExpress.ExpressApp.Security.v21.2"" >
      <SpecificVersion>False</SpecificVersion>
    </Reference>
	    <Reference Include=""DevExpress.ExpressApp.Security.Xpo.v21.2"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
");
            
            #line 119 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t <!--//report#13-->\r\n\t <!--//office#11#-->\r\n\r\n    <Reference Include=\"DevExpress" +
                    ".ExpressApp.Xpo.v21.2\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </R" +
                    "eference>\r\n\t<Reference Include=\"DevExpress.Images.v21.2\">\r\n\t  <SpecificVersion>F" +
                    "alse</SpecificVersion>\r\n    </Reference>\r\n\r\n    <Reference Include=\"DevExpress.P" +
                    "rinting.v21.2.Core\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </Refe" +
                    "rence>\r\n    <Reference Include=\"DevExpress.Data.v21.2\">\r\n      <SpecificVersion>" +
                    "False</SpecificVersion>\r\n    </Reference>\r\n    <Reference Include=\"DevExpress.Of" +
                    "fice.v21.2.Core\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </Referen" +
                    "ce>\r\n\r\n    <Reference Include=\"DevExpress.RichEdit.v21.2.Core\">\r\n      <Specific" +
                    "Version>False</SpecificVersion>\r\n    </Reference>\r\n    <Reference Include=\"DevEx" +
                    "press.ExpressApp.v21.2\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </" +
                    "Reference>\r\n    <Reference Include=\"DevExpress.ExpressApp.Web.v21.2\">\r\n      <Sp" +
                    "ecificVersion>False</SpecificVersion>\r\n      <Private>False</Private>\r\n    </Ref" +
                    "erence>\r\n    <Reference Include=\"DevExpress.Persistent.Base.v21.2\">\r\n      <Spec" +
                    "ificVersion>False</SpecificVersion>\r\n    </Reference>\r\n    <Reference Include=\"D" +
                    "evExpress.Persistent.BaseImpl.v21.2\">\r\n      <SpecificVersion>False</SpecificVer" +
                    "sion>\r\n    </Reference>\r\n    <Reference Include=\"DevExpress.Data.Desktop.v21.2\">" +
                    "\r\n      <SpecificVersion>False</SpecificVersion>\r\n      <Private>False</Private>" +
                    "\r\n    </Reference>\r\n    <Reference Include=\"DevExpress.Utils.v21.2\">\r\n      <Spe" +
                    "cificVersion>False</SpecificVersion>\r\n      <Private>False</Private>\r\n    </Refe" +
                    "rence>\r\n    <Reference Include=\"DevExpress.Web.ASPxThemes.v21.2\">\r\n      <Specif" +
                    "icVersion>False</SpecificVersion>\r\n    </Reference>\r\n    <Reference Include=\"Dev" +
                    "Express.Web.ASPxTreeList.v21.2\">\r\n      <SpecificVersion>False</SpecificVersion>" +
                    "\r\n      <Private>False</Private>\r\n    </Reference>\r\n\r\n    <Reference Include=\"De" +
                    "vExpress.Web.v21.2\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </Refe" +
                    "rence>\r\n    <Reference Include=\"DevExpress.Xpo.v21.2\">\r\n      <SpecificVersion>F" +
                    "alse</SpecificVersion>\r\n    </Reference>\r\n    <Reference Include=\"System\">\r\n    " +
                    "  <Private>False</Private>\r\n    </Reference>\r\n    <Reference Include=\"System.Con" +
                    "figuration\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference I" +
                    "nclude=\"System.Data\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Re" +
                    "ference Include=\"System.Data.DataSetExtensions\">\r\n      <Private>False</Private>" +
                    "\r\n    </Reference>\r\n    <Reference Include=\"System.Drawing\">\r\n      <Private>Fal" +
                    "se</Private>\r\n    </Reference>\r\n    <Reference Include=\"System.EnterpriseService" +
                    "s\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference Include=\"S" +
                    "ystem.Web\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference In" +
                    "clude=\"System.Web.ApplicationServices\">\r\n      <Private>False</Private>\r\n    </R" +
                    "eference>\r\n    <Reference Include=\"System.Web.DynamicData\">\r\n      <Private>Fals" +
                    "e</Private>\r\n    </Reference>\r\n    <Reference Include=\"System.Web.Entity\">\r\n    " +
                    "  <Private>False</Private>\r\n    </Reference>\r\n    <Reference Include=\"System.Web" +
                    ".Extensions\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference " +
                    "Include=\"System.Web.Mobile\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n" +
                    "    <Reference Include=\"System.Web.Services\">\r\n      <Private>False</Private>\r\n " +
                    "   </Reference>\r\n    <Reference Include=\"System.XML\">\r\n      <Private>False</Pri" +
                    "vate>\r\n    </Reference>\r\n    <Reference Include=\"System.Xml.Linq\">\r\n      <Priva" +
                    "te>False</Private>\r\n    </Reference>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <Conten" +
                    "t Include=\"Default.aspx\" />\r\n    <Content Include=\"Error.aspx\" />\r\n    <Content " +
                    "Include=\"Global.asax\" />\r\n    <Content Include=\"Images\\Logo.png\" />\r\n    <Conten" +
                    "t Include=\"Login.aspx\" />\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <Compile Include=\"" +
                    "Default.aspx.designer.cs\">\r\n      <DependentUpon>Default.aspx</DependentUpon>\r\n " +
                    "   </Compile>\r\n    <Compile Include=\"Error.aspx.designer.cs\">\r\n      <DependentU" +
                    "pon>Error.aspx</DependentUpon>\r\n    </Compile>\r\n    <Compile Include=\"Global.asa" +
                    "x.cs\">\r\n      <DependentUpon>Global.asax</DependentUpon>\r\n    </Compile>\r\n    <C" +
                    "ompile Include=\"Login.aspx.designer.cs\">\r\n      <DependentUpon>Login.aspx</Depen" +
                    "dentUpon>\r\n    </Compile>\r\n    <Compile Include=\"WebApplication.cs\">\r\n      <Sub" +
                    "Type>Component</SubType>\r\n    </Compile>\r\n    <Compile Include=\"Default.aspx.cs\"" +
                    ">\r\n      <DependentUpon>Default.aspx</DependentUpon>\r\n      <SubType>ASPXCodeBeh" +
                    "ind</SubType>\r\n    </Compile>\r\n    <Compile Include=\"Error.aspx.cs\">\r\n      <Dep" +
                    "endentUpon>Error.aspx</DependentUpon>\r\n      <SubType>ASPXCodeBehind</SubType>\r\n" +
                    "    </Compile>\r\n    <Compile Include=\"Login.aspx.cs\">\r\n      <DependentUpon>Logi" +
                    "n.aspx</DependentUpon>\r\n      <SubType>ASPXCodeBehind</SubType>\r\n    </Compile>\r" +
                    "\n    <Compile Include=\"Properties\\AssemblyInfo.cs\" />\r\n  </ItemGroup>\r\n  <ItemGr" +
                    "oup>\r\n    <EmbeddedResource Include=\"WebApplication.resx\">\r\n      <DependentUpon" +
                    ">WebApplication.cs</DependentUpon>\r\n      <SubType>Designer</SubType>\r\n    </Emb" +
                    "eddedResource>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <Content Include=\"Model.xafml" +
                    "\">\r\n      <SubType>Designer</SubType>\r\n    </Content>\r\n  </ItemGroup>\r\n  <ItemGr" +
                    "oup>\r\n    <ProjectReference Include=\"..\\dxTestSolution.Module\\dxTestSolution.Mod" +
                    "ule.csproj\">\r\n      <Project>{5F15837D-D1E5-44DC-92F0-4F2EBE9C3F8D}</Project>\r\n " +
                    "     <Name>dxTestSolution.Module</Name>\r\n    </ProjectReference>\r\n    <ProjectRe" +
                    "ference Include=\"..\\dxTestSolution.Module.Web\\dxTestSolution.Module.Web.csproj\">" +
                    "\r\n      <Project>{0C729AAD-7626-4668-A7F1-35F7D240489D}</Project>\r\n      <Name>d" +
                    "xTestSolution.Module.Web</Name>\r\n    </ProjectReference>\r\n  </ItemGroup>\r\n  <Ite" +
                    "mGroup>\r\n    <Content Include=\"Model.Desktop.xafml\" />\r\n    <Content Include=\"Mo" +
                    "del.Tablet.xafml\" />\r\n    <None Include=\"ReadMe.txt\" />\r\n    <Content Include=\"W" +
                    "eb.config\" />\r\n    <None Include=\"Web.Debug.config\">\r\n      <DependentUpon>Web.c" +
                    "onfig</DependentUpon>\r\n    </None>\r\n    <None Include=\"Web.EasyTest.config\">\r\n  " +
                    "    <DependentUpon>Web.config</DependentUpon>\r\n    </None>\r\n    <None Include=\"W" +
                    "eb.Release.config\">\r\n      <DependentUpon>Web.config</DependentUpon>\r\n    </None" +
                    ">\r\n  </ItemGroup>\r\n  <PropertyGroup>\r\n    <VisualStudioVersion Condition=\"\'$(Vis" +
                    "ualStudioVersion)\' == \'\'\">10.0</VisualStudioVersion>\r\n    <VSToolsPath Condition" +
                    "=\"\'$(VSToolsPath)\' == \'\'\">$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(V" +
                    "isualStudioVersion)</VSToolsPath>\r\n  </PropertyGroup>\r\n  <Import Project=\"$(MSBu" +
                    "ildBinPath)\\Microsoft.CSharp.targets\" />\r\n  <Import Project=\"$(VSToolsPath)\\WebA" +
                    "pplications\\Microsoft.WebApplication.targets\" Condition=\"\'$(VSToolsPath)\' != \'\'\"" +
                    " />\r\n  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v10.0\\" +
                    "WebApplications\\Microsoft.WebApplication.targets\" Condition=\"false\" />\r\n  <!-- T" +
                    "o modify your build process, add your task inside one of the targets below and u" +
                    "ncomment it. \r\n       Other similar extension points exist, see Microsoft.Common" +
                    ".targets.\r\n  <Target Name=\"BeforeBuild\">\r\n  </Target>\r\n  <Target Name=\"AfterBuil" +
                    "d\">\r\n  </Target>\r\n  -->\r\n  <ProjectExtensions>\r\n    <VisualStudio>\r\n      <Flavo" +
                    "rProperties GUID=\"{349c5851-65df-11da-9384-00065b846f21}\">\r\n        <WebProjectP" +
                    "roperties>\r\n          <UseIIS>True</UseIIS>\r\n          <AutoAssignPort>True</Aut" +
                    "oAssignPort>\r\n          <DevelopmentServerPort>2065</DevelopmentServerPort>\r\n   " +
                    "       <DevelopmentServerVPath>/</DevelopmentServerVPath>\r\n          <IISUrl>htt" +
                    "p://localhost:2065/</IISUrl>\r\n          <NTLMAuthentication>False</NTLMAuthentic" +
                    "ation>\r\n          <UseCustomServer>False</UseCustomServer>\r\n          <CustomSer" +
                    "verUrl>\r\n          </CustomServerUrl>\r\n          <SaveServerSettingsInUserFile>F" +
                    "alse</SaveServerSettingsInUserFile>\r\n        </WebProjectProperties>\r\n      </Fl" +
                    "avorProperties>\r\n    </VisualStudio>\r\n  </ProjectExtensions>\r\n</Project>\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
