// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class WebCsproj : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 FileName=@"\{0}.Web\{0}.Web.csproj"; 
            
            #line default
            #line hidden
            this.Write("\r\n<Project DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/m" +
                    "sbuild/2003\" ToolsVersion=\"4.0\">\r\n  <Import Project=\"$(MSBuildExtensionsPath)\\$(" +
                    "MSBuildToolsVersion)\\Microsoft.Common.props\" Condition=\"Exists(\'$(MSBuildExtensi" +
                    "onsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props\')\" />\r\n  <PropertyGroup>\r" +
                    "\n    <Configuration Condition=\" \'$(Configuration)\' == \'\' \">Debug</Configuration>" +
                    "\r\n    <Platform Condition=\" \'$(Platform)\' == \'\' \">AnyCPU</Platform>\r\n    <Produc" +
                    "tVersion>9.0.30729</ProductVersion>\r\n    <SchemaVersion>2.0</SchemaVersion>\r\n   " +
                    " <ProjectGuid>{82A6DBC9-B1B4-44E4-9718-55DF930CD349}</ProjectGuid>\r\n    <Project" +
                    "TypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f" +
                    "79efbc}</ProjectTypeGuids>\r\n    <OutputType>Library</OutputType>\r\n    <AppDesign" +
                    "erFolder>Properties</AppDesignerFolder>\r\n    <RootNamespace>dxTestSolution.Web</" +
                    "RootNamespace>\r\n    <AssemblyName>dxTestSolution.Web</AssemblyName>\r\n    <Target" +
                    "FrameworkVersion>v4.5.2</TargetFrameworkVersion>\r\n    <FileUpgradeFlags>\r\n    </" +
                    "FileUpgradeFlags>\r\n    <OldToolsVersion>3.5</OldToolsVersion>\r\n    <UpgradeBacku" +
                    "pLocation>\r\n    </UpgradeBackupLocation>\r\n    <TargetFrameworkProfile />\r\n    <U" +
                    "seIISExpress>true</UseIISExpress>\r\n    <IISExpressSSLPort>44300</IISExpressSSLPo" +
                    "rt>\r\n    <IISExpressAnonymousAuthentication>enabled</IISExpressAnonymousAuthenti" +
                    "cation>\r\n    <IISExpressWindowsAuthentication>disabled</IISExpressWindowsAuthent" +
                    "ication>\r\n    <IISExpressUseClassicPipelineMode>false</IISExpressUseClassicPipel" +
                    "ineMode>\r\n    <UseGlobalApplicationHostFile />\r\n  </PropertyGroup>\r\n  <PropertyG" +
                    "roup Condition=\" \'$(Configuration)|$(Platform)\' == \'Debug|AnyCPU\' \">\r\n    <Debug" +
                    "Symbols>true</DebugSymbols>\r\n    <DebugType>full</DebugType>\r\n    <Optimize>fals" +
                    "e</Optimize>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstants>DEBUG;TRAC" +
                    "E</DefineConstants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4<" +
                    "/WarningLevel>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'$(Configuratio" +
                    "n)|$(Platform)\' == \'Release|AnyCPU\' \">\r\n    <DebugType>pdbonly</DebugType>\r\n    " +
                    "<Optimize>true</Optimize>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstan" +
                    "ts>TRACE</DefineConstants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningL" +
                    "evel>4</WarningLevel>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'$(Confi" +
                    "guration)|$(Platform)\' == \'EasyTest|AnyCPU\' \">\r\n    <DebugSymbols>true</DebugSym" +
                    "bols>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstants>TRACE;DEBUG;EASYT" +
                    "EST</DefineConstants>\r\n    <DebugType>full</DebugType>\r\n    <PlatformTarget>AnyC" +
                    "PU</PlatformTarget>\r\n    <ErrorReport>prompt</ErrorReport>\r\n  </PropertyGroup>\r\n" +
                    "  <ItemGroup>\r\n\r\n\t  <Reference Include=\"DevExpress.DataAccess.v20.1\">\r\n      <Sp" +
                    "ecificVersion>False</SpecificVersion>\r\n    </Reference>\r\n");
            
            #line 65 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 if (HasReports){ 
            
            #line default
            #line hidden
            this.Write(@" <Reference Include=""DevExpress.ExpressApp.ReportsV2.v20.1"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.ExpressApp.ReportsV2.Web.v20.1"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.XtraReports.v20.1"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.XtraReports.v20.1.Extensions"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.XtraReports.v20.1.Web"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
");
            
            #line 81 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 } 
            
            #line default
            #line hidden
            
            #line 82 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 if (HasOffice){ 
            
            #line default
            #line hidden
            this.Write(@"    <Reference Include=""DevExpress.Office.v20.1.Core"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include=""DevExpress.RichEdit.v20.1.Core"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
	    <Reference Include=""DevExpress.RichEdit.v20.1.Export"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>

		 <Reference Include=""DevExpress.ExpressApp.Office.v20.1"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.ExpressApp.Office.Web.v20.1"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.RichEdit.v20.1.Core"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.Spreadsheet.v20.1.Core"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.Web.ASPxRichEdit.v20.1"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
<Reference Include=""DevExpress.Web.ASPxSpreadsheet.v20.1"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
");
            
            #line 111 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 } 
            
            #line default
            #line hidden
            
            #line 112 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 if (HasSecurity){ 
            
            #line default
            #line hidden
            this.Write(@"    <Reference Include=""DevExpress.ExpressApp.Security.v20.1"" >
      <SpecificVersion>False</SpecificVersion>
    </Reference>
	    <Reference Include=""DevExpress.ExpressApp.Security.Xpo.v20.1"">
      <SpecificVersion>False</SpecificVersion>
    </Reference>
");
            
            #line 119 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\WebCsproj.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t <!--//report#13-->\r\n\t <!--//office#11#-->\r\n\r\n    <Reference Include=\"DevExpress" +
                    ".ExpressApp.Xpo.v20.1\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </R" +
                    "eference>\r\n\t<Reference Include=\"DevExpress.Images.v20.1\" >\r\n\t  <SpecificVersion>" +
                    "False</SpecificVersion>\r\n    </Reference>\r\n\r\n    <Reference Include=\"DevExpress." +
                    "Printing.v20.1.Core\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </Ref" +
                    "erence>\r\n    <Reference Include=\"DevExpress.Data.v20.1\">\r\n      <SpecificVersion" +
                    ">False</SpecificVersion>\r\n    </Reference>\r\n    <Reference Include=\"DevExpress.E" +
                    "xpressApp.Images.v20.1\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </" +
                    "Reference>\r\n    <Reference Include=\"DevExpress.ExpressApp.v20.1\">\r\n      <Specif" +
                    "icVersion>False</SpecificVersion>\r\n    </Reference>\r\n    <Reference Include=\"Dev" +
                    "Express.ExpressApp.Web.v20.1\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n" +
                    "      <Private>False</Private>\r\n    </Reference>\r\n    <Reference Include=\"DevExp" +
                    "ress.Persistent.Base.v20.1\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n  " +
                    "  </Reference>\r\n    <Reference Include=\"DevExpress.Persistent.BaseImpl.v20.1\">\r\n" +
                    "      <SpecificVersion>False</SpecificVersion>\r\n    </Reference>\r\n    <Reference" +
                    " Include=\"DevExpress.Data.Desktop.v20.1\">\r\n      <SpecificVersion>False</Specifi" +
                    "cVersion>\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference Incl" +
                    "ude=\"DevExpress.Utils.v20.1\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n " +
                    "     <Private>False</Private>\r\n    </Reference>\r\n    <Reference Include=\"DevExpr" +
                    "ess.Web.ASPxThemes.v20.1\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    " +
                    "</Reference>\r\n    <Reference Include=\"DevExpress.Web.ASPxTreeList.v20.1\">\r\n     " +
                    " <SpecificVersion>False</SpecificVersion>\r\n      <Private>False</Private>\r\n    <" +
                    "/Reference>\r\n\r\n    <Reference Include=\"DevExpress.Web.v20.1\">\r\n      <SpecificVe" +
                    "rsion>False</SpecificVersion>\r\n    </Reference>\r\n    <Reference Include=\"DevExpr" +
                    "ess.Xpo.v20.1\">\r\n      <SpecificVersion>False</SpecificVersion>\r\n    </Reference" +
                    ">\r\n    <Reference Include=\"System\">\r\n      <Private>False</Private>\r\n    </Refer" +
                    "ence>\r\n    <Reference Include=\"System.Configuration\">\r\n      <Private>False</Pri" +
                    "vate>\r\n    </Reference>\r\n    <Reference Include=\"System.Data\">\r\n      <Private>F" +
                    "alse</Private>\r\n    </Reference>\r\n    <Reference Include=\"System.Data.DataSetExt" +
                    "ensions\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference Incl" +
                    "ude=\"System.Drawing\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Re" +
                    "ference Include=\"System.EnterpriseServices\">\r\n      <Private>False</Private>\r\n  " +
                    "  </Reference>\r\n    <Reference Include=\"System.Web\">\r\n      <Private>False</Priv" +
                    "ate>\r\n    </Reference>\r\n    <Reference Include=\"System.Web.ApplicationServices\">" +
                    "\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference Include=\"Syst" +
                    "em.Web.DynamicData\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Ref" +
                    "erence Include=\"System.Web.Entity\">\r\n      <Private>False</Private>\r\n    </Refer" +
                    "ence>\r\n    <Reference Include=\"System.Web.Extensions\">\r\n      <Private>False</Pr" +
                    "ivate>\r\n    </Reference>\r\n    <Reference Include=\"System.Web.Mobile\">\r\n      <Pr" +
                    "ivate>False</Private>\r\n    </Reference>\r\n    <Reference Include=\"System.Web.Serv" +
                    "ices\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference Include" +
                    "=\"System.XML\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n    <Reference" +
                    " Include=\"System.Xml.Linq\">\r\n      <Private>False</Private>\r\n    </Reference>\r\n " +
                    " </ItemGroup>\r\n  <ItemGroup>\r\n    <Content Include=\"Default.aspx\" />\r\n    <Conte" +
                    "nt Include=\"Error.aspx\" />\r\n    <Content Include=\"Global.asax\" />\r\n    <Content " +
                    "Include=\"Images\\Logo.png\" />\r\n    <Content Include=\"Login.aspx\" />\r\n  </ItemGrou" +
                    "p>\r\n  <ItemGroup>\r\n    <Compile Include=\"Default.aspx.designer.cs\">\r\n      <Depe" +
                    "ndentUpon>Default.aspx</DependentUpon>\r\n    </Compile>\r\n    <Compile Include=\"Er" +
                    "ror.aspx.designer.cs\">\r\n      <DependentUpon>Error.aspx</DependentUpon>\r\n    </C" +
                    "ompile>\r\n    <Compile Include=\"Global.asax.cs\">\r\n      <DependentUpon>Global.asa" +
                    "x</DependentUpon>\r\n    </Compile>\r\n    <Compile Include=\"Login.aspx.designer.cs\"" +
                    ">\r\n      <DependentUpon>Login.aspx</DependentUpon>\r\n    </Compile>\r\n    <Compile" +
                    " Include=\"WebApplication.cs\">\r\n      <SubType>Component</SubType>\r\n    </Compile" +
                    ">\r\n    <Compile Include=\"Default.aspx.cs\">\r\n      <DependentUpon>Default.aspx</D" +
                    "ependentUpon>\r\n      <SubType>ASPXCodeBehind</SubType>\r\n    </Compile>\r\n    <Com" +
                    "pile Include=\"Error.aspx.cs\">\r\n      <DependentUpon>Error.aspx</DependentUpon>\r\n" +
                    "      <SubType>ASPXCodeBehind</SubType>\r\n    </Compile>\r\n    <Compile Include=\"L" +
                    "ogin.aspx.cs\">\r\n      <DependentUpon>Login.aspx</DependentUpon>\r\n      <SubType>" +
                    "ASPXCodeBehind</SubType>\r\n    </Compile>\r\n    <Compile Include=\"Properties\\Assem" +
                    "blyInfo.cs\" />\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <EmbeddedResource Include=\"We" +
                    "bApplication.resx\">\r\n      <DependentUpon>WebApplication.cs</DependentUpon>\r\n   " +
                    "   <SubType>Designer</SubType>\r\n    </EmbeddedResource>\r\n  </ItemGroup>\r\n  <Item" +
                    "Group>\r\n    <Content Include=\"Model.xafml\">\r\n      <SubType>Designer</SubType>\r\n" +
                    "    </Content>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <ProjectReference Include=\".." +
                    "\\dxTestSolution.Module\\dxTestSolution.Module.csproj\">\r\n      <Project>{5F15837D-" +
                    "D1E5-44DC-92F0-4F2EBE9C3F8D}</Project>\r\n      <Name>dxTestSolution.Module</Name>" +
                    "\r\n    </ProjectReference>\r\n    <ProjectReference Include=\"..\\dxTestSolution.Modu" +
                    "le.Web\\dxTestSolution.Module.Web.csproj\">\r\n      <Project>{0C729AAD-7626-4668-A7" +
                    "F1-35F7D240489D}</Project>\r\n      <Name>dxTestSolution.Module.Web</Name>\r\n    </" +
                    "ProjectReference>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <Content Include=\"Model.De" +
                    "sktop.xafml\" />\r\n    <Content Include=\"Model.Tablet.xafml\" />\r\n    <None Include" +
                    "=\"ReadMe.txt\" />\r\n    <Content Include=\"Web.config\" />\r\n    <None Include=\"Web.D" +
                    "ebug.config\">\r\n      <DependentUpon>Web.config</DependentUpon>\r\n    </None>\r\n   " +
                    " <None Include=\"Web.EasyTest.config\">\r\n      <DependentUpon>Web.config</Dependen" +
                    "tUpon>\r\n    </None>\r\n    <None Include=\"Web.Release.config\">\r\n      <DependentUp" +
                    "on>Web.config</DependentUpon>\r\n    </None>\r\n  </ItemGroup>\r\n  <PropertyGroup>\r\n " +
                    "   <VisualStudioVersion Condition=\"\'$(VisualStudioVersion)\' == \'\'\">10.0</VisualS" +
                    "tudioVersion>\r\n    <VSToolsPath Condition=\"\'$(VSToolsPath)\' == \'\'\">$(MSBuildExte" +
                    "nsionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)</VSToolsPath>\r\n  </" +
                    "PropertyGroup>\r\n  <Import Project=\"$(MSBuildBinPath)\\Microsoft.CSharp.targets\" /" +
                    ">\r\n  <Import Project=\"$(VSToolsPath)\\WebApplications\\Microsoft.WebApplication.ta" +
                    "rgets\" Condition=\"\'$(VSToolsPath)\' != \'\'\" />\r\n  <Import Project=\"$(MSBuildExtens" +
                    "ionsPath32)\\Microsoft\\VisualStudio\\v10.0\\WebApplications\\Microsoft.WebApplicatio" +
                    "n.targets\" Condition=\"false\" />\r\n  <!-- To modify your build process, add your t" +
                    "ask inside one of the targets below and uncomment it. \r\n       Other similar ext" +
                    "ension points exist, see Microsoft.Common.targets.\r\n  <Target Name=\"BeforeBuild\"" +
                    ">\r\n  </Target>\r\n  <Target Name=\"AfterBuild\">\r\n  </Target>\r\n  -->\r\n  <ProjectExte" +
                    "nsions>\r\n    <VisualStudio>\r\n      <FlavorProperties GUID=\"{349c5851-65df-11da-9" +
                    "384-00065b846f21}\">\r\n        <WebProjectProperties>\r\n          <UseIIS>True</Use" +
                    "IIS>\r\n          <AutoAssignPort>True</AutoAssignPort>\r\n          <DevelopmentSer" +
                    "verPort>2065</DevelopmentServerPort>\r\n          <DevelopmentServerVPath>/</Devel" +
                    "opmentServerVPath>\r\n          <IISUrl>http://localhost:2065/</IISUrl>\r\n         " +
                    " <NTLMAuthentication>False</NTLMAuthentication>\r\n          <UseCustomServer>Fals" +
                    "e</UseCustomServer>\r\n          <CustomServerUrl>\r\n          </CustomServerUrl>\r\n" +
                    "          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>\r\n  " +
                    "      </WebProjectProperties>\r\n      </FlavorProperties>\r\n    </VisualStudio>\r\n " +
                    " </ProjectExtensions>\r\n</Project>\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
