// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DXTicketBase.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\XPOConnectionHelper.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class XPOConnectionHelper : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\XPOConnectionHelper.tt"
 FileName=@"\{0}\ConnectionHelper.cs"; 
            
            #line default
            #line hidden
            this.Write("//------------------------------------------------------------------------------\r" +
                    "\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//\r\n//     Chan" +
                    "ges to this file may cause incorrect behavior and will be lost if\r\n//     the co" +
                    "de is regenerated.\r\n// </auto-generated>\r\n//------------------------------------" +
                    "------------------------------------------\r\nusing System;\r\nusing DevExpress.Xpo;" +
                    "\r\nusing DevExpress.Data.Filtering;\r\nusing System.Collections.Generic;\r\nusing Sys" +
                    "tem.ComponentModel;\r\nusing System.Configuration;\r\nusing dxTestSolutionXPO.Module" +
                    ".BusinessObjects;\r\nusing DevExpress.Xpo.DB;\r\n\r\nnamespace dxTestSolutionXPO {\r\n  " +
                    "  public static class ConnectionHelper {\r\n        static Type[] persistentTypes " +
                    "= new Type[] {\r\n            typeof(Contact),typeof(MyTask)\r\n        };\r\n        " +
                    "public static Type[] GetPersistentTypes() {\r\n            Type[] copy = new Type[" +
                    "persistentTypes.Length];\r\n            Array.Copy(persistentTypes, copy, persiste" +
                    "ntTypes.Length);\r\n            return copy;\r\n        }\r\n        static string Con" +
                    "nectionString;\r\n        static bool UseInMemoryStore;\r\n        public static voi" +
                    "d Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe =" +
                    " false) {\r\n            ConnectionString = ConfigurationManager.ConnectionStrings" +
                    "[\"ConnectionString\"].ConnectionString;\r\n            if(threadSafe) {\r\n          " +
                    "      var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCrea" +
                    "teOption);\r\n                var dictionary = new DevExpress.Xpo.Metadata.Reflect" +
                    "ionDictionary();\r\n                dictionary.GetDataStoreSchema(persistentTypes)" +
                    ";\r\n                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, pr" +
                    "ovider);\r\n            } else {\r\n                XpoDefault.DataLayer = XpoDefaul" +
                    "t.GetDataLayer(ConnectionString, autoCreateOption);\r\n            }\r\n\t\t    ");
            
            #line 46 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\XPOConnectionHelper.tt"
 if (UseInMemory){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tUseInMemoryStore = true;\r\n\t\t    ");
            
            #line 48 "C:\Dropbox\C#\DXTicketsBase\DXTicketBase\DXTicketBase\TextTemplates\XPOConnectionHelper.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            
            if(UseInMemoryStore) {
                XpoDefault.DataLayer = new SimpleDataLayer(new InMemoryDataStore());
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption) {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect) {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption) {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
