//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXTicketBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string TicketNo { get; set; }
        public string Subject { get; set; }
        public string Comment { get; set; }
        public bool IsFolderDelete { get; set; }
    }
}
